RailsCastDemo/config/routes.rb
RailsCastDemo::Application.routes.draw do
  resources :users
  resources :projects
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # Episode 35 Custom REST Actions
  resources :tasks do
  	collection do
  		get 'completed'
  	end
  	member do
  		put 'complete'
  	end
  end # end Episode 35

  # Episode 42 with_options
  with_options to: "projects#index" do |path|
    path.match "test1"
    path.match "test2"
    path.match "test3"
  end # end Episode 42

  root :to => "tasks#index"
end

RailsCastDemo/app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :description

  has_many :tasks

  validates :name, :description, presence: true

  def self.all_names
    find(:all).collect(&:name)
  end

	# Episode 37 Simple Search Form
  def self.search(query)
  	if query
			find(:all, :conditions => ['name LIKE ?', '%' + query + '%'])
  	else
  		find(:all)
  	end
  end
end

RailsCastDemo/app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :complete, :name, :project_id, :priority, :due_at

  belongs_to :project, :counter_cache => true

  def category_name
  	read_attribute("category_name") || category.name
  end

  def self.find_incomplete(options={})
  	with_scope :find => options do
	  	find_all_by_complete(false)
	  end
  end

	# Episode 15 Fun with Find Conditions
		# Task.sum(:priority)
	  # SELECT SUM("tasks"."priority") AS sum_id FROM "tasks"

	 	# Task.sum(:priority, :conditions =>["complete = ?", false])
	 	# SELECT SUM("tasks"."priority") AS sum_id FROM "tasks" WHERE (complete = 'f')

	 	# Task.maximum(:priority)
	 	# SELECT MAX("tasks"."priority") AS max_id FROM "tasks"

	 	# Task.average(:priority)
	 	# SELECT AVG("tasks"."priority") AS avg_id FROM "tasks"

	 	# Project.first.tasks.sum(:priority)
	 	# SELECT SUM("tasks"."priority") AS sum_id FROM "tasks" WHERE "tasks"."project_id" = 1
end

RailsCastDemo/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :middle_initial, :email, :password, :password_confirmation

  has_secure_password

  validates_uniqueness_of :email
  # Ep 41 Conditional Validations
  validates_presence_of :first_name, :last_name, :email, :on => :create
  validates_presence_of :password, :if => :should_validate_password?
  attr_accessor :updating_password
  # End Ep 41

  def full_name
  	[first_name, middle_initial_with_full_stop, last_name].compact.join(" ")
  end

  def middle_initial_with_full_stop
  	"#{middle_initial}." unless middle_initial.blank?
  end

  # Ep 41; set in the controller update action
  def should_validate_password?
  	updating_password || new_record?
  end
end

RailsCastDemo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
	  def current_user
	  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
	  end
	  helper_method :current_user

	  def authorize
	  	redirect_to login_url, alert: "Please log in or sign up first!" if current_user.nil?
	  end
end

RailsCastDemo/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	layout :user_layout

	def new
		@project = Project.new
		render :layout => 'projects'
	end

	def create
		@project = Project.new(params[:project])
		if params[:preview_button] || !@project.save
			render :new
		else
			flash[:notice] = "Successfully created project!"
			redirect_to project_path(@project)
		end
	end

	def index
		# Episode 37 Simple Search Form
		@projects = Project.search(params[:search])
		# use the projects layout only for this action
		render :layout => 'projects'
	end

	def show
		@project = Project.find(params[:id])
		@tasks = @project.tasks.find_incomplete :limit => 3, :order =>'created_at DESC'
	end

	protected
	  def user_layout
	  	# if current_user.admin?
	  	if true
	  		"admin"
	  	else
	  		"application"
	  	end
	  end
end

RailsCastDemo/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to root_url, notice: "Logged in!"
  	else
  		flash.now.alert = "Email or password is invalid."
  		render :new
  	end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

RailsCastDemo/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_filter :authorize, only: :complete

	def index
		@tasks = Task.find_incomplete(:include => :project)
		#@tasks = Task.all(:include => :project)
		#@tasks = Task.order("projects.name").includes(:project)
		#@tasks = Task.order("projects.name").joins(:project).select("tasks.*, projects.name as project_name")
		#Ep29: group_by_month
		@task_months = @tasks.group_by { |t| t.due_at.beginning_of_month } #END Ep29: group_by_month
	end

	def incomplete
		@tasks = Task.find_all_by_complete(false)
	end

	def last_incomplete
		@task = Task.find_by_complete(false, :order => 'created_at DESC')
	end
	# Episode 15 Fun with Find Conditions
		# Task.find(:all, :conditions => ["complete = ? AND priority = ?", false, 2])
		# SELECT "tasks".* FROM "tasks" WHERE (complete = 'f' AND priority = 2)

		# Task.find(:all, :conditions => { complete: false, priority: [1,3] })
		# SELECT "tasks".* FROM "tasks" WHERE "tasks"."complete" = 'f' AND "tasks"."priority" IN (1, 3)

		# Task.find_all_by_priority(1..3)
		# SELECT "tasks".* FROM "tasks" WHERE ("tasks"."priority" BETWEEN 1 AND 3)

	# Episode 15 Custom REST Actions
	def complete
		@task = Task.find(params[:id])
		@task.update_attribute(:complete, true)
		flash[:notice] = "Successfully marked task as complete."
		redirect_to completed_tasks_path
	end

	def completed
		@tasks = Task.find(:all, :conditions => 'complete = "t"')
		#@tasks = Task.find_all_by_complete(true)
	end
	# end Episode 15
end

RailsCastDemo/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_url, notice: "Thank you for signing up!"
		else
			render :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.updating_password = true # Ep 41 conditional validations

		if @user.update_attributes(params[:user])
			redirect_to user_path(@user), notice: "Successfully updated user"
		else
			render :edit
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:notice] = "User successfully deleted"
		redirect_to users_path
	end
end

RailsCastDemo/app/helpers/application_helper.rb
module ApplicationHelper
end

RailsCastDemo/app/helpers/projects_helper.rb
module ProjectsHelper
end

RailsCastDemo/app/helpers/sessions_helper.rb
module SessionsHelper
end

RailsCastDemo/app/helpers/tasks_helper.rb
module TasksHelper
end

RailsCastDemo/app/helpers/users_helper.rb
module UsersHelper
	# Episode 40
	# Move this to the Application Helper in order to share with other model view templates
	def admin_area(&block) # being called in the user show template
		# if current_user.admin?
		if true
			concat content_tag(:span, capture(&block), class: 'admin')
		end
	end
end

RailsCastDemo/app/views/layouts/admin.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<%= yield :head %>
	</head>
	<body>
		<div id="container">
			<h1>Admin Layout!</h1>
			<%= yield %>
		</div>
	</body>
</html>

RailsCastDemo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Railscastdemo</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<% flash.each do |key, msg| %>
			<%= content_tag :p, msg, id: key %>
		<% end %>
		<div id="container">
			<div class="user_header">
				<% if current_user %>
					Logged in as <%= current_user.email %> |
					<%= link_to 'Log Out', logout_path %>
				<% else %>
					<%= link_to "Sign Up", signup_path %> or
					<%= link_to "Log In", login_path %>
				<% end %>
			</div>
			<%= yield %>
		</div>
	</body>
</html>

RailsCastDemo/app/views/layouts/projects.html.erb
<h1>Projects Layout!</h1>
<%= yield %>

RailsCastDemo/app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
	<% if @project.errors.any? %>
		<div class="error_messages">
			<h2><%= pluralize @project.errors.count, 'error' %> prohibited this project from being saved</h2>
			<p>There were problems with the following fields:</p>
			<ul>
				<% @project.errors.full_messages.each do |error| %>
					<li><%= error %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<% if params[:preview_button] %>
		<div id="preview">
			<h2><%= @project.name %></h2>
			<%= @project.description %>
		</div>
	<% end %>

	<%= f.label :name %><br>
	<%= f.text_field :name %><br>
	<%= f.label :description %><br>
	<%= f.text_area :description %><br>
	<%= f.submit "Submit" %>
	<%= f.submit "Preview", name: "preview_button" %>
<% end %>

RailsCastDemo/app/views/projects/index.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag 'projects' %>
<% end %>

<h2>Projects</h2>

<%= form_tag projects_path, :method => 'get' do %>
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", :name => nil %>
	</p>
<% end %>

<table>
<% for project in @projects %>
	<tr>
		<td><%= link_to project.name, project_path(project) %></td>
		<td><small>(<%= pluralize project.tasks.size, 'task' %>)</small></td>
	</tr>
<% end %>
</table>

RailsCastDemo/app/views/projects/new.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag 'projects' %>
<% end %>

<h1>New Project</h1>

<%= render 'form' %>

RailsCastDemo/app/views/projects/show.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag 'admin' %>
<% end %>

<div id="project">
	<p>Project: <%= @project.name %></p>
	<p>Description: <%= @project.description %></p>
</div>

RailsCastDemo/app/views/tasks/completed.html.erb
<h1>Completed Tasks</h1>

<ul>
	<% @tasks.each do |task| %>
		<li><%= task.name %></li>
	<% end %>
</ul>

RailsCastDemo/app/views/tasks/index.html.erb
<h3>Incomplete Tasks</h3>
<hr>
<% @task_months.each do |month, tasks| %>
	<h4><%= month.strftime("%B %Y") %></h4>
	<table>
	  <% tasks.each do |task| %>
	    <tr>
	    	<td>
	    		<b><%= link_to task.name, task_path(task) %></b>
		    	<small> in <%= task.project.name %></small>
		    	<!-- ( due on <%#= task.due_at.to_date.to_s(:long) %>) -->
		    	(due on <%= task.due_at.to_s(:due_date) %>)
		    	| <%= link_to "Mark as Complete", complete_task_path(task), method: :put %>
		    </td>
		  </tr>
	  <% end %>
  </table>
<% end %>

<hr>
<%= link_to "Add A New Task", new_task_path %>
| <%= link_to "Completed Tasks", completed_tasks_path %>

RailsCastDemo/app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2>Oops...Looks like you made <%= pluralize @user.errors.count, 'error' %></h2>
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="field">
		<%= f.label :first_name %><br>
		<%= f.text_field :first_name %>
	</div>
	<div class="field">
		<%= f.label :middle_initial %><br>
		<%= f.text_field :middle_initial %>
	</div>
	<div class="field">
		<%= f.label :last_name %><br>
		<%= f.text_field :last_name %>
	</div>
	<div class="field">
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %><br>
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation %><br>
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit 'Sign Up' %>
	</div>
<% end %>

RailsCastDemo/app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

RailsCastDemo/app/views/users/index.html.erb
<h3>Users List</h3>

<table>
	<% @users.in_groups_of(3, false) do |row_users| %>
	  <tr>
			<% for user in row_users %>
		  	<td><%= link_to user.full_name, user_path(user) %></td>
			<% end %>
	  </tr>
  <% end %>
</table>

RailsCastDemo/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

RailsCastDemo/app/views/users/show.html.erb
<h1>Profile</h1>
<p>
	Name:
	<%= @user.full_name %>
</P>
<%= link_to 'Users List', users_path %>

<% admin_area do %>
	<%= link_to 'Delete User', user_path(@user), method: :delete, confirm: "Click OK to delete current user" %>
<% end %>